image: alpine/edge
packages:
  - nodejs
  - yarn
artifacts:
  - obsidian-bibeltext-plugin.tar.gz
tasks:
- setup: |
    yarn install
- build: |
    yarn run build
- package: |
    tar -c manifest.json main.js styles.css | gzip > obsidian-bibeltext-plugin.tar.gz

